name: release

on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Use Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      -
        name: Set up Docker Buildx
        run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
      -
        name: Build image for release
        run: |
          docker buildx build \
            --builder multi-builder \
            -t paloma-release \
            --target release \
            . 
      -
        name: Release
        run: |
          docker run \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            paloma-release
